services:
  - type: web
    name: helpdesk-laravel
    runtime: image
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: TRUSTED_PROXIES
        value: "*"
      # Base de datos - TiDB Serverless (llenar en Render Dashboard)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      # ImageKit (llenar en Render Dashboard)
      - key: IMAGEKIT_PUBLIC_KEY
        value: public_V771PZno9+e341QdTAy6BDa9Yqs=
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/helpdeskgdc

